### ISSUE TITLE
Build HDF5 filter in CI builds

### ISSUE THREAD

**Issue by jack-pappas** [Blosc/c-blosc#140]
The ``BUILD_HDF5_FILTER`` option in CMakeLists.txt defaults to ``OFF``; it currently isn't overridden for CI builds so the blosc HDF5 filter isn't built/tested.

I'm opening this issue as a reminder to implement the necessary steps in the CI builds to fetch the HDF5 source (or binaries with source headers, if available) then build the blosc HDF5 filter against it so we know it compiles and works on some basic level.

**Comment by FrancescAlted** [comment]
Well, I am lately leaning to separate the HDF5 filter implementation to its own repository hanging from Blosc umbrella.  The thing is that since its inception, c-blosc evolved into a pretty much independent compressor, so I think this move makes sense.

Once the HDF5 filter has its own repo, we can add HDF5 testing for CI.  @jack-pappas if you agree, I can create the repo and give you developer permissions there.

**Comment by jack-pappas** [comment]
That's fine with me. Once you create the repo I'll work on setting up the CI builds for it.

**Comment by FrancescAlted** [comment]
Cool.  So I created the Blosc/hdf5 repo and added you as a developer.  Please feel free to start populating it.  Later we should decide how to make the transition and remove the hdf5 file from c-blosc repo itself.

**Comment by FrancescAlted** [comment]
The Blosc/hdf5 has been created and populated with tests for Unix, and the hdf5 filter has been removed from this repo.  @jack-pappas you are welcome if you want to complete the new hdf5 repo with tests for Windows and other improvements.
