### ISSUE TITLE
compress_ctx and decompress_ctx with pre-initialized context?

### ISSUE THREAD

**Issue by stevengj** [Blosc/c-blosc#277]
For a multi-threaded application, it seems a bit wasteful in `blosc_compress_ctx` and `blosc_decompress_ctx` that it creates and destroys a new context on every call.   I would rather allocate the contexts myself (one per caller thread, i.e. in a thread-local global) and pass them in.

Would you consider exporting `blosc_context_create` and `blosc_context_destroy` functions to allocate an opaque context pointer, and then export `blosc_[de]compress_context` functions that take this pointer as an argument (instead of the `compressor, blocksize, numinternalthreads` arguments, which would be set by `blosc_context_create`)?

**Comment by FrancescAlted** [comment]
Hi @stevengj. Thanks for the PR. I am open to include your PR in C-Blosc, but provided that C-Blosc2 is in beta already, I'd suggest to migrate this there instead. This will allow you to start using the [new features in C-Blosc2](http://blosc.org/posts/blosc2-first-beta/), while contributing to testing it.

**Comment by stevengj** [comment]
Ah, thanks — I didn't even realize that you had switched to a [separate repo](https://github.com/Blosc/c-blosc2) for the next blosc version.

(Why did you switch to a new repository instead of just using the same repo, and putting the old c-blosc maintainance on a branch?)

**Comment by FrancescAlted** [comment]
Well, when I started my work in Blosc2 I was not sure on whether I was going to be able to make it backward compatible or not, so this is why I decided to go with another repo. In the end it happened that I achieved the new format to be backward compatible, although we are gonna have to have the header called differently (blosc2.h instead of blosc.h) as well as the library itself (libblosc2 instead of libblosc2). Regarding the API, Blosc2 is intended to be backward compatible too (but more testing is still needed).  By using separate repos we ha more flexibility in maintaining Blosc1 while devoloping Blosc2.

**Comment by FrancescAlted** [comment]
@stevengj you may also be interested on [Caterva](https://github.com/Blosc/Caterva), a sibling project that allows to define multidimensional arrays on top of Blosc2 containers.  There also is [cat4py](https://github.com/Blosc/cat4py), a Python wrapper for Caterva, but I suppose that you would be more interested in a Julia wrapper ;-)
