### ISSUE TITLE
Support for szip?

### ISSUE THREAD

**Issue by rsignell-usgs** [Blosc/c-blosc#283]
Does Blosc suppport szip?   
https://support.hdfgroup.org/doc_resource/SZIP/

I'm hoping that it's possible for Zarr, which uses Blosc, to support any type of compression supported by HDF5, so that HDF5 may reliably be converted to Zarr.

**Comment by FrancescAlted** [comment]
Hi Rich.  No, Blosc does not support szip, and it has never been an option because of szip's restrictive license for commercial uses.  At any rate, I don't think adding support for szip inside Blosc is the right way to allow for HDF5 conversions to Zarr; probably it is going to be much better if you add szip support independently in Zarr.

**Comment by cgohlke** [comment]
FWIW, [libaec](https://github.com/erget/libaec) includes a free (BSD) drop-in replacement for the SZIP library.
