### ISSUE TITLE
Support Quantile Compression codec

### ISSUE THREAD

**Issue by mwlon** [Blosc/c-blosc#331]
Quantile Compression is a recent compressor for numerical sequences with a stable format. Instead of LZ77 or LZ78 approaches, it operates on the numerical distribution, typically coming close to the Shannon entropy and achieving 35% higher compression ratio than other codecs given the same compression time. Its decompression speed is nearly as fast as ZStandard. Since Blosc focuses on loading in numerical data, Quantile Compression will likely be very beneficial.

Some questions to sort out:
* Quantile Compression supports delta encoding up to order 7. Should we use Blosc's delta encoding preprocessor or Quantile Compression's?
* I have yet to dig into Blosc's internals. Quantile Compression's inputs must be input in a typed way, e.g. a vector of 64-bit floats, but Blosc says it operates on binary data. Hopefully there is a zero-cost way to convert between the two.

**Comment by FrancescAlted** [comment]
Hi.  Quantile Compression sounds nice indeed.  However, instead of providing a PR for C-Blosc, I suggest to use C-Blosc2 because it supports [plugins for codecs](https://www.blosc.org/posts/registering-plugins/).  The plugin mechanism allows you to experiment with it as a user-registered one, and then we can initiate the process to registering globally.

Regarding your questions:

* The delta encoding in Blosc is a filter (pre-codec) that can be used in combination with other filters in the pipeline (up to 6 in C-Blosc2).  So you may want to experiment which one gives better results.
* Blosc is agnostic about types, but it still let you specify the `typesize`.  Such typesize is [stored in the header](https://github.com/Blosc/c-blosc2/blob/main/README_CHUNK_FORMAT.rst#header), so it can be retrieved during decompression so as to inform to the codec.  So yes, for Blosc 64-bit vectors is interchangeable with binary, so no conversions are involved at all.

Hope this helps

**Comment by mwlon** [comment]
@FrancescAlted I'm trying to set up the plugin, but having trouble because I'm new to C / CMake. Quantile Compression is in rust, so I need to run the cargo build as a dependency for this plugin. Is there anyone who could help me link this together in this PR? https://github.com/Blosc/c-blosc2/pull/397

**Comment by FrancescAlted** [comment]
See my answer in PR https://github.com/Blosc/c-blosc2/pull/397.  Closing.
